### ISSUE TITLE
Not compatible with NodeMCU / ESP8266

### ISSUE THREAD

**Issue by heinduplessis** [fabriziop/TalkingLED#1]
When compiling I get the error:

`TalkingLED.cpp:112:22: error: 'unit8_t' was not declared in this scope`

(Will this work in normal arduino?)

After fixing that, anther error pops up. Just seems to be type issues.

**Comment by fabriziop** [comment]
I just pushed a fix. There was a typo in 'set' function argument type and the prototype of 'set' function was missing into include file.
Now it compiles for both NodeMCU and Arduino Nano/Uno.
