### ISSUE TITLE
Incorrect digitalWrite call in set()

### ISSUE THREAD

**Issue by keestux** [fabriziop/TalkingLED#3]
The arguments of `digitalWrite` are swapped.
```
void TalkingLED::set(uint8_t aLEDStatus) {
  LEDStatus = aLEDStatus;
  digitalWrite(LEDStatus,LEDPin);
```

**Comment by fabriziop** [comment]
Just now, I uploaded the fix for the incorrect swap of "set" method arguments. 
The new library version is 0.1.4 .
