### ISSUE TITLE
Support ESP32

### ISSUE THREAD

**Issue by amontes80** [fabriziop/TalkingLED#4]
How compatible ESP8266 code is with ESP32?
Can the library support esp32?

**Comment by fabriziop** [comment]
Currently not, but the extension to ESP32 may be quite easy, I think. It is needed to add the pin number of  the ESP32 on board LED and which pin levels correspond to LED on/off status. Unfortunately, I have no ESP32 board to test such an extension.

**Comment by fabriziop** [comment]
Added support for ESP32 processor

**Comment by fabriziop** [comment]
Added support for ESP32 processor
